name: Build and push Docker image

on:
  workflow_call:

jobs:
  build-and-push-image:
    name: Build and push Docker image to Github container registry
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get all relevant that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v36
        with:
          files_yaml_from_source_file: .github/changed_files.yml

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files-yaml.outputs.all_all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        if: steps.changed-files-yaml.outputs.all_any_changed == 'true'

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        if: steps.changed-files-yaml.outputs.all_any_changed == 'true'

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        if: steps.changed-files-yaml.outputs.all_any_changed == 'true'

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
        if: steps.changed-files-yaml.outputs.all_any_changed == 'true'
