name: publish to gh pages

on:
  workflow_run:
    workflows: [ROS]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-deploy-documentation:
    name: Build and deploy documentation to Github Pages
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-22.04
    container: ghcr.io/san-soucie/sgdrfros:main
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Install dev requirements
        run: |
          python3 -m pip install -r dev.requirements.txt
          sudo apt-get update && sudo apt-get install -y --no-install-recommends git-lfs

      - name: Build documentation
        run: |
          . /ros2_ws/install/setup.sh
          cd sgdrf/docs/source
          sphinx-build . ../../../site -b html

      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: site
