name: ROS

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build and push Docker image to Github container registry
    uses: ./.github/workflows/docker.yml
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/san-soucie/sgdrfros:main
    needs: build-and-push-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/test/

  lint:
    name: Lint (ament_${{ matrix.linter }})
    runs-on: ubuntu-latest
    needs: build-and-push-image
    container: ghcr.io/san-soucie/sgdrfros:main
    strategy:
      fail-fast: false
      matrix:
        linter:
          [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        uses: ./.github/actions/lint/
        env:
          LINTER: ${{ matrix.linter }}
