name: ROS

on:
  push:
    branches:
      - main

jobs:
  build-and-push-image:
    name: Build and push Docker image to Github container registry
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      packages: write
  test:
    name: Test
    runs-on: ubuntu-latest
    container: ghcr.io/san-soucie/sgdrfros:main
    steps:
      - uses: actions/checkout@v2
      - name: Setup ROS tooling
        uses: ros-tooling/setup-ros@v0.6
        with:
          required-ros-distributions: iron
      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ hashFiles('sgdrf/setup.py') }}

      - name: Run ROS ci
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          target-ros2-distro: iron

  lint:
    name: Lint (ament_${{ matrix.linter }})
    runs-on: ubuntu-latest
    needs: build-and-push-image
    container: ghcr.io/san-soucie/sgdrfros:main
    strategy:
      fail-fast: false
      matrix:
        linter:
          [cppcheck, cpplint, uncrustify, lint_cmake, xmllint, flake8, pep257]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        uses: ./.github/actions/lint/
        env:
          LINTER: ${{ matrix.linter }}
